USE amit;

CREATE TABLE STUDENTINFORMATION (
    stdid INT(5),
    stdname VARCHAR(20),
    dob DATE,
    doj DATE,
    fee INT(5),
    gender CHAR );
 
 DESC STUDENT;


INSERT INTO STUDENTINFORMATION (stdid, stdname, dob, doj, fee, gender)
VALUES (1, 'amogh', '2001-01-10', '2001-10-05', 10000, 'M');

INSERT INTO STUDENTINFORMATION (stdid, stdname, dob, doj, fee, gender)
VALUES (2, 'aamit', '2019-11-3', '2001-10-26', 11000, 'M');

ALTER TABLE STUDENTINFORMATION ADD PHONE_NO INT(10);

ALTER TABLE STUDENTINFORMATION 
RENAME COLUMN PHONE_NO  TO STUDENT_NO ;

ALTER TABLE STUDENTINFORMATION RENAME TO STUDENTINFO;

SELECT * FROM STUDENTINFO;

ALTER TABLE STUDENTINFO DROP COLUMN gender;

DELETE FROM STUDENTINFO WHERE STDID = 2;